steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/partners-portal-gem:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_N8N_API_URL=$_N8N_URL'
      - '.'

  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/partners-portal-gem:latest']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'partners-portal-gem'
      - '--image'
      - 'gcr.io/$PROJECT_ID/partners-portal-gem:latest'
      - '--region'
      - 'europe-central2'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_N8N_API_URL=$_N8N_URL'

images:
  - 'gcr.io/$PROJECT_ID/partners-portal-gem:latest'

substitutions:
  _N8N_URL: 'https://n8n.boni.tools/webhook/partner-portal'